apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
 
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    {{- if .Values.selectorLabels }}
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
    {{- end }}
 
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      {{- if .Values.selectorLabels }}
      labels:
        {{- toYaml .Values.selectorLabels | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      containers:
        - name: {{ .Chart.Name }}
 
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
 
          ports:
            - name: http
              containerPort: {{ .Values.containerPort.port }}
 
 
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
 
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
 
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
 
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
 
          env:
            - name: {{ index .Values.statefulset 0 "passKey" }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-{{ index $.Values.secret 1 "name" }}-secret
                  key: {{ index .Values.secret 1 "key" }}
            - name: {{ index $.Values.statefulset 0 "userKey" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-{{ index $.Values.configMap 0 "name" }}-configmap
                  key: {{ index $.Values.configMap 0 "user" "userKey" }}
            - name: {{ index $.Values.statefulset 0  "dbKey" }}
              valueFrom:
                configMapKeyRef:
                  name:  {{ $.Release.Name }}-{{ index $.Values.configMap 0 "name" }}-configmap
                  key: {{ index $.Values.configMap 0 "db" "dbKey" }}
 
            - name: DATABASE_URL
              value: {{ index $.Values.statefulset 0 "database-protocol" }}$({{ index $.Values.statefulset 0 "userKey" }}):$({{ index .Values.statefulset 0 "passKey" }})@{{index $.Values.service 1 "name"}}:{{index $.Values.service 1 "port"}}/$({{ index $.Values.statefulset 0  "dbKey" }})

              
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}