{{- range .Values.persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}

  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}

  annotations:
    {{- if .annotations.enabled }}
    helm.sh/resource-policy: {{ .annotations.policy | quote }}
    {{- end }}

spec:
  accessModes:
    {{- range .accessModes }}
    - {{ . | default "ReadWriteMany" }}
    {{- end }}
  resources:
    requests:
      storage: {{ .capacity}}
  storageClassName: {{ .storageClass}}
  volumeName: {{ .volumeName }}

{{- end }}
