{{- range .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
spec:
  {{- if .selectorLabels }}
  selector:
    {{- toYaml .selectorLabels | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .port }} 
      targetPort: {{ .targetPort }}
      {{- if eq .type "NodePort" }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: {{ .protocol }}
  type: {{ .type }}
{{- end }}
