apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workout-management-app.fullname" . }}-postgres-configmap
  labels: 
    {{- include "workout-management-app.postgresLabels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgresConfig.user}}
  POSTGRES_DB: {{ .Values.postgresConfig.db}}
