apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "workout-management-app.fullname" . }}-image-storage-pv
  labels:
    {{- include "workout-management-app.labels" . | nindent 4 }}

spec:
  capacity:
    storage: {{ .Values.PersistentVolume.capacity}}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.PersistentVolume.accessMode}}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.PersistentVolume.storageClass}}
  hostPath:
    path: {{ .Values.PersistentVolume.hostPath}}
    type: DirectoryOrCreate
