apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "workout-management-app.fullname" . }}-image-storage-pvc
  labels:
    {{- include "workout-management-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.PersistentVolumeClaim.accessMode}}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.capacity}}
  storageClassName: {{ .Values.PersistentVolumeClaim.storageClass}}
  volumeName: {{ .Values.PersistentVolumeClaim.volumeName }}


