apiVersion: v1
kind: Service
metadata:
  name: {{ include "workout-app.fullname" . }}-postgres-db
  #name: postgres-db
  labels:
    app: postgres
spec:
  type: {{ .Values.postgresService.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.postgresService.port | default 5432 }}
      targetPort: {{ .Values.postgresService.targetPort | default 5432 }}
      protocol: TCP
  selector:
    app: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "workout-app.fullname" . }}-web-app
  labels:
    {{- include "workout-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webAppService.type | default "NodePort" }}
  selector:
    {{- include "workout-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.webAppService.port | default 5000 }}
      targetPort: {{ .Values.webAppService.targetPort | default 5000 }}
      {{- if .Values.webAppService.nodePort }}
      nodePort: {{ .Values.webAppService.nodePort }}
      {{- end }}

